### PR TITLE
Added parseFloat in goog.string.format

### PR DESCRIPTION
**Pull request by lomonosv**
toFixed doesn't work without parseFloat

### CODE REVIEW

**Comment by Ubehebe** [comment]
@lomonosv You need to [sign a CLA](https://github.com/google/closure-library/blob/master/CONTRIBUTING) before we can merge this PR.

**Comment by lomonosv** [comment]
Thanks for your answer. I signed a CLA.

**Comment by Ubehebe** [comment]
@lomonosv This PR now has 12 commits instead of 1. I think you may need to rebase onto HEAD?

**Comment by nanaze** [comment]
Please update this PR. Right now it is not mergeable.

**Comment by nanaze** [comment]
merged with minor edits

**Pull request merged**
