### PR TITLE
Fix multiplication carry in Integer

### PR DESCRIPTION
**Pull request by gfredericks**
Fixes issue #703

### CODE REVIEW

**Comment by gfredericks** [comment]
I don't understand [this](https://travis-ci.org/google/closure-library/builds/150660466) build failure. It seems to have a compile error on completely unrelated code.

**Comment by gfredericks** [comment]
I added an extra test for the smallest failing case I could find. Travis reports that the latest master build failed as well, so I'm not sure how to tell if I did something wrong. The integer tests pass on my machine.

**Comment by xcthulhu** [comment]
I found the original bug with a more elaborate test involving modular square roots:

https://github.com/Sepia-Officinalis/secp256k1/blob/master/test/secp256k1/math_test.cljs#L22

@gfredericks We talked out of band about using this test, should I implement it here?

**Comment by xcthulhu** [comment]
Similarly, modular multiplicative inverse is a good way of testing both multiplication and division algorithms are implemented - these would be sort of *math integration tests* but they are strong validations that everything is implemented properly.

**Pull request merged**
