### PR TITLE
Add travis script to run lint on pull requests

### PR DESCRIPTION
**Pull request by joeltine**

### CODE REVIEW

**Comment by joeltine** [comment]
OMG. It actually works! It's a Christmas miracle!

**Comment by joeltine** [comment]
@concavelenz Did you want to take a look at this before merging?

**Comment by concavelenz** [comment]
Usually, we ask folks to squash there commits before merging.  Can you do that?

**Comment by joeltine** [comment]
Commits squashed.

**Comment by concavelenz** [comment]
merge conflict?

**Pull request merged**
