### PR TITLE
Fix common typo: 'b' -> correct assertion values

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
Seems CI failures are not related:
```
Jul 02, 2020 12:27:54 AM com.github.jsdossier.jscomp.TypeCollectionPass$TypeCollector processSymbol
WARNING: skipping goog.global; references global this
/home/travis/build/google/closure-library/closure/goog/a11y/aria/announcer.js:57: WARNING - [JSC_DEPRECATED_PROP_REASON] Property inherits of type goog has been deprecated:  Use ECMAScript class syntax instead.
goog.inherits(goog.a11y.aria.Announcer, goog.Disposable);
^^^^^^^^^^^^^
/home/travis/build/google/closure-library/closure/goog/array/array.js:322: WARNING - [JSC_DEPRECATED_PROP_REASON] Property bind of type goog has been deprecated:  use `=> {}` or Function.prototype.bind instead.
        f = goog.bind(f, opt_obj);
            ^^^^^^^^^
/home/travis/build/google/closure-library/closure/goog/array/array.js:367: WARNING - [JSC_DEPRECATED_PROP_REASON] Property bind of type goog has been deprecated:  use `=> {}` or Function.prototype.bind instead.
        f = goog.bind(f, opt_obj);
            ^^^^^^^^^

```

**Comment by 12wrigja** [comment]
Thanks for the PR! I'm going to fix up the external CI issues and then we can merge this in.

**Comment by 12wrigja** [comment]
I believe the CI issues are now fixed as of 65c605abf8a0e5f289bb63ac3757609e52005885 - please rebase your changes on that and we can merge this in.

**Comment by 12wrigja** [comment]
This was merged in as 1effe31eb45b91e2efd45ef3df9adf67afbc480a.

**Pull request closed without merging**
