### PR TITLE
Update XPF and EUR currencies

### PR DESCRIPTION
**Pull request by DavidSkazy**
XPF currency was wrong => update XPF currency.
Most countries in Euro area are using the € in last position with a space => update EUR currency.
More details -> http://publications.europa.eu/code/fr/fr-370303.htm (French)

### CODE REVIEW

**Comment by joeltine** [comment]
@fabalbon, I don't see currency.js listed here: https://github.com/google/closure-library/wiki/Internationalization-(i18n)-changes-in-Closure-Library. Isn't it also auto-generated from CLDR?

**Comment by fabalbon** [comment]
@joeltine currency.js is the only locale data file not being auto-generated. Still, we try be consistent with the data on CLDR.

**Comment by joeltine** [comment]
Thanks @fabalbon.

@DavidSkazy, we're running global tests on this change internally to see if we break any existing users. @fabalbon should have an idea of the impact soon.

**Comment by fabalbon** [comment]
Thanks for pointing out the bug in the **XPF** currency, we are updating it internally according to the data available on CLDR and it will be out on the next closure release. Regarding **EUR**, it has a broader impact thus we won't update at this moment.

We strongly discourage the use of the APIs on `currency.js` to get the the currency sign’s position, several of these functions have already been deprecated. This is because the position of the currency sign depends on the display locale, but the data on `goog.i18n.currency.CurrencyInfo` is based on the currency’s default locale, which is a problem with currencies such as **EUR** which don't have a default locale.

To format currencies we recommend the use of `goog.i18n.NumberFormat(goog.i18n.NumberFormat.Format.CURRENCY, “EUR")` which uses locale-dependent data which is auto-generated from CLDR.

**Comment by joeltine** [comment]
I'm assuming this was fixed in the last release https://github.com/google/closure-library/releases

**Pull request closed without merging**
