### PR TITLE
Add @license comment to base.js

### PR DESCRIPTION
**Pull request by pirosikick**
I'd like to add `@license` comment to avoid removing the license text when minifying.

### CODE REVIEW

**Comment by pirosikick** [comment]
@googlebot I signed it!

My company(Cybozu. inc) has already signed the CLA. Would you confirm that?

**Comment by rrdelaney** [comment]
Internal issue created at http://b/146013791

**Comment by shicks** [comment]
I've actually already got an internal change that does this.

**Comment by shicks** [comment]
We're just working out all the prerequisites to merge it first.  It breaks a lot of internal tests. :-(

**Comment by teppeis** [comment]
@pirosikick It seems to be fixed in master https://github.com/google/closure-library/commit/1fe1bd873b1b772cca7de983cbaf72ef4011de0b

**Pull request closed without merging**
