### PR TITLE
New NPM Release v20190215.0.0

### PR DESCRIPTION
**Pull request by blickly**

### CODE REVIEW

**Comment by teppeis** [comment]
@blickly Please merge and publish new version to npm!

**Comment by blickly** [comment]
Sorry I missed that! I'm trying to both do a library release for the first time and better document the steps so that we're more consistent with the closure library releases; it looks like I missed the `npm publism` step in my instructions.

I think it's released now (https://www.npmjs.com/package/google-closure-library) and that it's not necessary to merge the http://go/gh/google/closure-library/tree/npm-v20190215.0.0 branch into master.  Let me know if any of the assumptions I've made aren't true.

Thanks for catching!

**Comment by teppeis** [comment]
@blickly Thanks!

**Comment by teppeis** [comment]
@blickly closure-deps is not updated
https://www.npmjs.com/package/google-closure-deps

**Comment by blickly** [comment]
@jplaisted, do you know what that package is and how it is released?

**Comment by jplaisted** [comment]
https://www.npmjs.com/package/google-closure-library

I think we have a script to release it internally. But should be as simple as go to the commit the release was made at an run `npm publish`

**Comment by blickly** [comment]
OK, I think this should be (finally) released.

**Pull request closed without merging**
