### PR TITLE
Perf improvements for sha1.js, sha2.js, and sha2_64b.js

### PR DESCRIPTION
**Pull request by coruus**
Please see https://github.com/google/closure-library/pull/322 for the original PR. This is rebased and squashed.

CC @meheffernan @nanaze

This is rebased and squashed. @nanaze: Are the changes sufficient to make this work on Kindle Fire?

### CODE REVIEW

**Comment by Ubehebe** [comment]
@coruus @meheffernan This PR causes at least five unit tests to fail:

```
closure/crypt/sha12mc_test
com.google.testing.javascript.runner.core.TimeoutError: Test timed out in 240.105 seconds after exceeding timeout of 240 seconds.
G_testRunner not detected: test failed to load
```
```
closure/crypt/hmac_test.testHmac
com.google.testing.javascript.runner.core.JavaScriptFailure: ERROR in testHmac
test 1 failed
Expected <b617318655057264e28bc0b6fb378c8ef146be00> (String) but was <0bd1bed50cc0b29f08a8c4390f6667100dd60ef0> (String)
```
```
closure/crypt/pbkdf2_test.testPBKDF2
com.google.testing.javascript.runner.core.JavaScriptFailure: ERROR in testPBKDF2
mismatch at index 0: 
Expected <12> (Number) but was <2> (Number)
```
```
closure/crypt/sha1_test.testHashing
com.google.testing.javascript.runner.core.JavaScriptFailure: ERROR in testHashing
Expected <da39a3ee5e6b4b0d3255bfef95601890afd80709> (String) but was <0a39a3ee0e6b4b0d0255bfef056018900fd80709> (String)
```
```
closure/crypt/sha1_test.testLength
com.google.testing.javascript.runner.core.JavaScriptFailure: ERROR in testLength
Expected <a9993e364706816aba3e25717850c26c9cd0d89d> (String) but was <02957e6f0a07ff52028650bc02c2e22b0030929a> (String)
```
I've rewritten the history of the project so that this PR was never merged. We need a better process for testing PRs before merging, to avoid headaches like this.

**Comment by coruus** [comment]
Hmm. I'm somewhat perplexed: When I tested this recently, I'm fairly
certain that all tests were passing.

Is this on a specific target, or all targets?

I know that all tests were passing on V8/amd64 when I first submitted the
previous PR...

In that thread, there was a mention of some platform-specific issues,
though?

Do you have a preferred CI setup that I can test against?

**Comment by Ubehebe** [comment]
@coruus In order to land this PR, you'll need to point me to a CI setup showing all Closure unit tests passing. I'd like to set up Travis for this project, but I can't commit to doing it anytime soon. Maybe you can help?

**Comment by coruus** [comment]
Sounds like fun.

**Comment by coruus** [comment]
Hmm. So, actually, the problem was fairly trivial (and not platform-specific). Here's the diff:

```diff
diff --git a/closure/goog/crypt/sha1.js b/closure/goog/crypt/sha1.js
index a1979ea..a96cc96 100644
--- a/closure/goog/crypt/sha1.js
+++ b/closure/goog/crypt/sha1.js
@@ -179,7 +179,7 @@ goog.crypt.Sha1.prototype.compress_ = function(buf, opt_offset) {
   // performance by about 10% on Chrome 35.
   for (i = 16; i < 80; i++) {
     t = W[(i - 3) & 15] ^ W[(i - 8) & 15] ^ W[(i - 14) & 15] ^ W[i & 15];
-    W[i & 15] = (((t << 1) | (t >>> 31)) & 0xfffffff) | 0;
+    W[i & 15] = (((t << 1) | (t >>> 31)) & 0xffffffff) | 0;
     if (i < 40) {
       if (i < 20) {
         f = d ^ (b & (c ^ d));
@@ -206,11 +206,11 @@ goog.crypt.Sha1.prototype.compress_ = function(buf, opt_offset) {
     a = t;
   }
 
-  this.chain_[0] = ((this.chain_[0] + a) & 0xfffffff) | 0;
-  this.chain_[1] = ((this.chain_[1] + b) & 0xfffffff) | 0;
-  this.chain_[2] = ((this.chain_[2] + c) & 0xfffffff) | 0;
-  this.chain_[3] = ((this.chain_[3] + d) & 0xfffffff) | 0;
-  this.chain_[4] = ((this.chain_[4] + e) & 0xfffffff) | 0;
+  this.chain_[0] = ((this.chain_[0] + a) & 0xffffffff) | 0;
+  this.chain_[1] = ((this.chain_[1] + b) & 0xffffffff) | 0;
+  this.chain_[2] = ((this.chain_[2] + c) & 0xffffffff) | 0;
+  this.chain_[3] = ((this.chain_[3] + d) & 0xffffffff) | 0;
+  this.chain_[4] = ((this.chain_[4] + e) & 0xffffffff) | 0;
 };
```

**Comment by coruus** [comment]
And see #404 for the fixed version.

**Pull request merged**
