### PR TITLE
Fix disposable leak in abstractbubbleplugin.js

### PR DESCRIPTION
**Pull request by toshi-toma**

### CODE REVIEW

**Comment by toshi-toma** [comment]
@googlebot I signed it!

**Comment by rrdelaney** [comment]
Internal Google issue http://b/145816464 created.

**Comment by shicks** [comment]
@toshi-toma It looks like the CLA isn't taking - do you want to try it again?

**Comment by toshi-toma** [comment]
@shicks 
Thank you for looking!! 
I'll try it again.

**Comment by toshi-toma** [comment]
@googlebot I signed it!

**Comment by shicks** [comment]
Sorry this has been so difficult.  I'm looking at the logs and it looks like it's not finding a signature corresponding to the email address on the commit: `t...-t...@cybozu.co.jp` (eliding a bit for some minimal privacy) - is it possible you're signing with a different email address?

**Comment by shicks** [comment]
@toshi-toma 
Sorry this has been so difficult. I'm looking at the logs and it looks like it's not finding a signature corresponding to the email address on the commit: t...-t...@cybozu.co.jp (eliding a bit for some minimal privacy) - is it possible you're signing with a different email address?

**Pull request closed without merging**
