### PR TITLE
Refine type returns of createElement()

### PR DESCRIPTION
**Pull request by psam44**
For https://github.com/google/closure-library/issues/570

### CODE REVIEW

**Comment by psam44** [comment]
I signed the CLA

**Comment by shicks** [comment]
@joeltine - does the travis failure look legit or is it a tool failure?  The error I see under "details" is

Line 1085, E:0251: Invalid suppression type: newCheckTypes
Line 1086, E:0217: Missing @return JsDoc in function with non-trivial return

which doesn't seem relevant to this change.

**Comment by joeltine** [comment]
It's not legit. Those are known lint issues w/ base.js.

**Comment by shicks** [comment]
@psam44 can you squash all these commits so that we can pull it in as a single commit?

To do this:

    git rebase -i master

and then change all but the first `pick` to `squash`.  Then you can rebase it on top of `upstream/master` (or whatever you've named our repo's remote).  When you push the branch back to your fork, you'll need to use `git push -f` to force it to rewrite your history (otherwise it will tell you to pull and merge, which undoes everything you'd just done).

**Comment by psam44** [comment]
Superseded by https://github.com/google/closure-library/pull/584

**Pull request closed without merging**
