### PR TITLE
compile error fix

### PR DESCRIPTION
**Pull request by dbwhddn10**
https://github.com/codedust/libphonenumber-api/blob/master/build.sh#L43
my environment is java jdk 1.8.0, python 3.4.3

[Review on Reviewable](https://reviewable.io/reviews/google/closure-library/474)

### CODE REVIEW

**Comment by concavelenz** [comment]
Nathan can you take a look at this?

**Comment by nanaze** [comment]
What is the output  of "java -version" on your system?

**Comment by dbwhddn10** [comment]
my java version is 1.8.0_45

**Comment by nanaze** [comment]
LGTM

**Pull request merged**
