### PR TITLE
Add Tier 2 support for CLF currency

### PR DESCRIPTION
**Pull request by TimovanderKamp**

### CODE REVIEW

**Comment by TimovanderKamp** [comment]
CLA

**Comment by TimovanderKamp** [comment]
CLA

**Comment by shicks** [comment]
Internal Google issue http://b/130240960 created.

**Comment by shicks** [comment]
I've mailed this internally as cl/300001130

**Comment by 12wrigja** [comment]
This was merged in 3276bf2c4fcbaff85c76c1e7cffc3d9be1aeecfd, but this PR was not marked as merged (probably an issue with our externalization workflow). Closing.

**Pull request closed without merging**
