### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by zchee**

### CODE REVIEW

**Comment by MatrixFrog** [comment]
Thanks! Can you sign the CLA?

**Comment by zchee** [comment]
[This](https://github.com/google/closure-library/blob/master/AUTHORS) ?

**Comment by nanaze** [comment]
see CLA instructions: https://github.com/google/closure-library/blob/master/CONTRIBUTING

**Comment by zchee** [comment]
Ok, I was submitted to CLA.

**Pull request merged**
