### PR TITLE
Fix textarea for Microsoft Edge (unit tests now pass)

### PR DESCRIPTION
**Pull request by anwerso**

### CODE REVIEW

**Comment by anwerso** [comment]
I signed it!

**Comment by concavelenz** [comment]
This is a good change, the only question I have is if we should invert the logic here, so we are only checking for old IE:

!(goog.userAgent.IE && !goog.userAgent.isDocumentModeOrHigher(11))

**Comment by anwerso** [comment]
I thought about inverting logic too. In that case textarea will also work in Presto (no need to extra condition).

**Comment by concavelenz** [comment]
@anwerso   Were you going to invert the condition? The lint failure should have been fixed separately.

**Pull request merged**
