### PR TITLE
goog.json improvement

### PR DESCRIPTION
**Pull request by Leoperd87**
goog.json improvement
(https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval)

### CODE REVIEW

**Comment by Leoperd87** [comment]
I signed it!

**Comment by joeltine** [comment]
Can you please be more explicit about what exactly this change intends to accomplish? A unit test would help as well.

**Comment by Leoperd87** [comment]
My improvement mean that developer should select by his own how should work goog.json (same as goog.array). Because some environments didn't allow eval by security reasons.

**Comment by concavelenz** [comment]
There are number of problems with this patch (it is a breaking change, it introduces a define in the wrong namespace, etc).  Can you be specific as to the problem you were facing and what you motivation was for this change.

**Pull request closed without merging**
