### PR TITLE
Add yargs as a dependency

### PR DESCRIPTION
**Pull request by jplaisted**
Planning on switching from argparse to yargs:

1) Yargs is much nicer to use
2) Yargs is more popular
3) Yargs has better documentation
4) Yargs has a cute pirate theme

### CODE REVIEW

**Comment by teppeis** [comment]
@jplaisted yargs has been added to the deps, but it's not used yet.
Is switching working in progress? or can I work on it?

**Comment by teppeis** [comment]
Also, yargs v12 is not latest now. v13 is the latest.

**Comment by jplaisted** [comment]
Thanks for pinging. I needed to make this PR and then continue with the work, which I clearly left hanging (it would've ideal to do it in the same PR...). For now due to some technical restrictions we need to use v12.

**Comment by teppeis** [comment]
@jplaisted Great.
If "some technical restrictions" means dropping support for Node v6, it's reverted recently in v13.2.2 https://github.com/yargs/yargs/pull/1308

**Pull request merged**
