### PR TITLE
Fix highlightedIndex_ not being set in setHighlightedIndex

### PR DESCRIPTION
**Pull request by ghosttie**
As discussed in https://github.com/google/closure-library/issues/731

### CODE REVIEW

**Comment by ghosttie** [comment]
I'm not sure I understand why the The Travis CI build failed

**Comment by mashedcode** [comment]
@ghosttie well it's because if `setHighlightedIndex(-1)` is called the highlight should be removed. Obviously no child at the index `-1` is found and `this.highlightedIndex_ > -1` will always evaluate to `false` in that case and because of your change. Therefore you can't remove the current highlight anymore and the test fails.

You obviously only want to set the highlighted index to something `> -1` if there's actually a child that will be highlighted anyway so that's another issue.

**Comment by ghosttie** [comment]
@mashedcode thanks, that was very helpful - I'll be more self-sufficient next time

**Comment by ghosttie** [comment]
I don't think 

> Failed: Modal dialog present: The Acrobat DC PDF browser plug-in is missing.

is my fault...

**Comment by joeltine** [comment]
Sauce Labs *shakes fist*!

That failure is unrelated to this CL. It's a Sauce Labs infra platform issue.

**Comment by ghosttie** [comment]
How about

> Failed: ERROR The test with session id c52b1bf454734499adc752c66df1edcd has already finished, and can't receive further commands.

**Comment by joeltine** [comment]
Same. It means we ran out of VMs on Sauce Labs. It typically happens when multiple PRs/commits come in at the same time.

**Comment by ghosttie** [comment]
Does it automatically retry or do I need to do something?

**Comment by joeltine** [comment]
I restarted it.

**Comment by ghosttie** [comment]
> closure/goog/net/streams/jsonstreamparser_test.html timed out after 45s!

This is less fun that I was expecting

**Comment by joeltine** [comment]
I wouldn't be too concerned getting Travis green. It's pretty obvious your change is introducing any new breakages.

**Comment by joeltine** [comment]
PR looks good. Can you please squash your commits into 1 and add a unit test to https://github.com/google/closure-library/blob/master/closure/goog/ui/container_test.js?

**Comment by joeltine** [comment]
@ghosttie waiting on the last comment before merging.

**Comment by ghosttie** [comment]
Sorry, I do intend to do squash the commits and add a unit test

**Comment by ghosttie** [comment]
When I was writing the tests I realized it was working even without my changes.  highlightedIndex_ is set in goog.ui.Container.prototype.handleHighlightItem so it doesn't need to be set directly in setHighlightedIndex.  I can't think why I had the problem in the first place.

**Pull request closed without merging**
