### PR TITLE
Fix the IE10+ SCRIPT65535 error in goog.events.FileDropHandler

### PR DESCRIPTION
**Pull request by rikuayanokozy**
See more at https://github.com/google/closure-library/issues/485

### CODE REVIEW

**Comment by rikuayanokozy** [comment]
I signed it!

**Comment by concavelenz** [comment]
Can you add a test case that would fail without your change?

**Comment by rikuayanokozy** [comment]
Um... I have not idea about construct a DataTransfer object in test.

**Comment by joeltine** [comment]
You don't want to construct the actual DataTransfer object. You can just create a mock object. The existing test already does this. For example: https://github.com/google/closure-library/blob/eb26f425dbd99a70d2955d8fcc892f2fd0178acb/closure/goog/events/filedrophandler_test.js#L55

**Comment by rikuayanokozy** [comment]
Thanks for ur help. I added test case.

**Comment by rikuayanokozy** [comment]
Okay, I use defineProperty instead of defineSetter, now the test is compatible with IE8+. The test renamed to testEffectAllowedExceptionIsCaught, unneeded eventdispatches and assertions has been removed. And now indent with 2.

**Comment by rikuayanokozy** [comment]
OK, I'll commit soon.
The event DRAGENTER is needed, because of [event dragenter set dndContainsFiles_](https://github.com/rikuayanokozy/closure-library/blob/f13fd37ca06a5df76b073e1dd7c3723825c24774/closure/goog/events/filedrophandler.js#L151-L155) and [onElemDrop_ need it](https://github.com/rikuayanokozy/closure-library/blob/f13fd37ca06a5df76b073e1dd7c3723825c24774/closure/goog/events/filedrophandler.js#L217).

**Comment by joeltine** [comment]
The PR  LGTM minus the quotes thing. I'l just change it myself before merging.

**Pull request merged**
