### PR TITLE
Fix for issue #876

### PR DESCRIPTION
**Pull request by ivanixgames**
Thumb in goog.ui.Slider widget drifts off when MoveToPointEnabled is true and thumb div is styled with offset properties (margin-top, margin-left);

Please see https://github.com/google/closure-library/issues/876

### CODE REVIEW

**Comment by ivanixgames** [comment]
I signed it! CLA

**Comment by shicks** [comment]
Sorry that we've let this sit for so long.  Is it still relevant?

**Comment by brad4d** [comment]
Internal Google issue http://b/142064937 created.

**Comment by shicks** [comment]
Merged in ed1785bf558c7119186f89163a01898a8a873ae0

**Pull request closed without merging**
